name: Build Bicep and output ARM template
on:
  push:
    paths:
      - "bicep/**"
    branches: ["master"]
  workflow_dispatch:

env:
  BICEP_PATH: ./bicep

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Bicep Build
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: ${{ env.BICEP_PATH }}/main.bicep
          outputFilePath: ${{ env.BICEP_PATH }}/azuredeploy.json
