name: Build Bicep and output ARM template
on:
  push:
    paths:
      - "bicep/**"
      - ".github/workflows/bicep-to-arm.yml"
    branches: ["master"]
  workflow_dispatch:

env:
  BICEP_PATH: ./bicep

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: |
          echo 
          if [ "$1" != "" ]  #if parameter exists, use as base folder 
            then cd "$1"
            fi
          pwd
          ls -R | grep ":$" |   
            sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
          # 1st sed: remove colons
          # 2nd sed: replace higher level folder names with dashes
          # 3rd sed: indent graph three spaces
          # 4th sed: replace first dash with a vertical bar
          if [ `ls -F -1 | grep "/" | wc -l` = 0 ]   # check if no folders
            then echo "   -> no sub-directories"
            fi
          echo
          exit\
        shell: bash

      - name: Bicep Build
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: ${{ env.BICEP_PATH }}/main.bicep
          outputFilePath: ${{ env.BICEP_PATH }}/azuredeploy.json
